### ISSUE TITLE
Embedding Egyptian fonts fails

### ISSUE THREAD

**Issue by gidsg** [guardian/open-platform-site#17]
Requesting the Guardian fonts fails
When you GET http://pasteup.guim.co.uk/fonts/latin1/Guardian-Egyp-Web-Semibold.woff it returns a 403, I think this is a security restriction around font embedding. I think @kaelig is the best person to discuss how to embed the fonts.

**Comment by phamann** [comment]
We maintain a domain whitelist against the pasteup.guim.co.uk domain. If you let me know what your hostname is I can add it to the referrer whitelist in Fastly.

**Comment by mchv** [comment]
This is expected and will work from [open-platform.theguardian.com](http://open-platform.theguardian.com) when the [CNAME will be created](https://jira.gutools.co.uk/browse/WSA-1584).
