### ISSUE TITLE
Clarify that phrase search no longer works

### ISSUE THREAD

**Issue by annapowellsmith** [guardian/open-platform-site#27]
Phrase search no longer works. See https://groups.google.com/forum/#!topic/guardian-api-talk/8EAtdReJ_Js

Ideally, re-enable phrase search, but I'm not sure where to raise that as an issue.

**Comment by gidsg** [comment]
Thanks for raising @annapowellsmith please see the response at: https://groups.google.com/d/msg/guardian-api-talk/8EAtdReJ_Js/w6JvOr34uboJ I will close this issue and we have raised an issue internally for this.

**Comment by gidsg** [comment]
I don't believe we make reference to Phrase search supporting anything other than free text in the current documentation (http://open-platform.theguardian.com/documentation/) so I don't think there is anything to fix in the docs but do shout if you think different.

**Comment by cb372** [comment]
@annapowellsmith We've just released support for boolean operators and phrase search. 

You can now search for things like:
- "david beckham"
- obama AND bush
- (obama OR clinton) AND bush

e.g. here's a phrase search for "david beckham":
http://content.guardianapis.com/search?q=%22david%20beckham%22&api-key=test

We've also added a section to [the documentation](http://open-platform.theguardian.com/documentation/) about this new feature.

Please give it a try and let us know on the Google group if you have any problems.
