### ISSUE TITLE
Top nav overlaps at smaller viewports

### ISSUE THREAD

**Issue by gidsg** [guardian/open-platform-site#8]
# Steps to reproduce

Go to: http://guardian.github.io/open-platform-site/explore/ on an iphone 
OR
Reduce your browser width
# Actual Results

Nav overlaps at smaller viewports
![img_0437](https://cloud.githubusercontent.com/assets/1764158/3467617/5c25f0bc-0293-11e4-9239-403c6becf73f.PNG)
# Expected Results

Nav does not overlap at smaller viewports, 
(there is enough real-estate so I think it is a case of improving the CSS)

**Comment by mchv** [comment]
Thank's @gidsg I will fix it !

**Comment by gidsg** [comment]
fixed
